services:
  git-cache:
    build:
      context: git-cache
    ports:
      - "8765:8765"
    volumes:
      - repo-cache:/repo-cache
    restart: unless-stopped

volumes:
  repo-cache:
    name: repo-cache