#!/bin/sh
set -x

docker compose down
docker image rm git-cache-proxy-git-cache --force
docker volume rm repo-cache --force
docker compose up -d

# use this to view container logs:
docker compose logs -f
#
# or use this to debug 'git-cache-handler.sh':
# docker compose exec git-cache tail -f /var/log/git-cache/progress.log